/**
 * Frontend-specific type definitions
 *
 * This module extends the base `Child` interface from `backend/types.ts` to provide
 * frontend-specific types for React components and application state. All types maintain
 * compatibility with the existing JSON data structure generated by the backend.
 *
 * @module frontend/src/types
 */

import type { Child, AlbumMetadata, AlbumFile } from '../../../backend/types';

/**
 * Re-export the base Child interface for convenience
 *
 * This allows frontend code to import Child directly from the frontend types module
 * while maintaining a single source of truth in the backend/types.ts file.
 */
export type { Child, AlbumMetadata, AlbumFile };
export type { AlbumThemesConfig } from './albumThemes';

/**
 * Index metadata structure from index.json
 *
 * Contains root album information and site metadata generated by the backend.
 * This file serves as the entry point for the frontend to discover the root album.
 */
export interface IndexMetadata {
  /** Root album ID */
  rootAlbumId: number;
  /** Root album JSON filename (e.g., "7.json") */
  rootAlbumFile: string;
  /** Site name from root album title */
  siteName: string | null;
  /** Site description from root album description */
  siteDescription: string | null;
  /** ISO timestamp when index.json was generated */
  generatedAt: string;
  /** Path-based URL path to album ID. Keys are path strings (e.g. "/albums/photos"), values are album IDs. */
  pathIndex?: Record<string, number>;
  /** Additional root album metadata */
  metadata: {
    rootAlbumId: number;
    rootAlbumTitle: string | null;
    rootAlbumDescription: string | null;
    rootAlbumTimestamp: number | null;
  };
}

/**
 * Album type - represents a gallery album item
 *
 * Albums are discriminated from images by the `type` field being 'GalleryAlbumItem'.
 * Albums have null values for width, height, thumb_width, and thumb_height since
 * they are containers, not images.
 *
 * Albums may have thumbnail fields (thumbnailPathComponent, thumbnailPhotoId,
 * thumbnailWidth, thumbnailHeight) when they contain photos. These fields are
 * extracted from the first photo in the album during backend processing.
 */
export type Album = Child & {
  type: 'GalleryAlbumItem';
};

/**
 * Image type - represents a gallery photo item
 *
 * Images are discriminated from albums by the `type` field being 'GalleryPhotoItem'.
 * Images have non-null width and height values, and may have thumbnail dimensions
 * if a thumbnail derivative exists.
 */
export type Image = Child & {
  type: 'GalleryPhotoItem';
};

/**
 * Discriminated union type for album or image items
 *
 * This union type allows type narrowing based on the `type` discriminator field.
 * Use type guards (isAlbum, isImage) to narrow the type in conditional blocks.
 */
export type AlbumOrImage = Album | Image;

/**
 * Type guard function to check if a Child is an Album
 *
 * @param child - The child item to check
 * @returns True if the child is an Album (type is 'GalleryAlbumItem')
 *
 * @example
 * ```typescript
 * const item: Child = { ... };
 * if (isAlbum(item)) {
 *   // item is now narrowed to Album type
 *   console.log(item.type); // 'GalleryAlbumItem'
 * }
 * ```
 */
export function isAlbum(child: Child): child is Album {
  return child.type === 'GalleryAlbumItem';
}

/**
 * Type guard function to check if a Child is an Image
 *
 * @param child - The child item to check
 * @returns True if the child is an Image (type is 'GalleryPhotoItem')
 *
 * @example
 * ```typescript
 * const item: Child = { ... };
 * if (isImage(item)) {
 *   // item is now narrowed to Image type
 *   console.log(item.type); // 'GalleryPhotoItem'
 * }
 * ```
 */
export function isImage(child: Child): child is Image {
  return child.type === 'GalleryPhotoItem';
}

/**
 * Route parameters for album and image routes
 *
 * Used with React Router for type-safe route parameter access.
 * Supports both single ID routes (/album/:id, /image/:id) and
 * hierarchical routes (/album/:albumId/image/:imageId).
 */
export interface RouteParams {
  /** ID parameter from route (e.g., /album/:id or /image/:id) */
  id?: string;
  /** Album ID parameter from hierarchical route (e.g., /album/:albumId/image/:imageId) */
  albumId?: string;
  /** Image ID parameter from hierarchical route (e.g., /album/:albumId/image/:imageId) */
  imageId?: string;
  /** Path-based route splat (path="*"), e.g. "seg1/seg2" or "seg1/seg2/image/123" */
  '*'?: string;
}

/**
 * Breadcrumb item representing a single level in the navigation hierarchy
 *
 * Used to build breadcrumb navigation paths showing the album hierarchy.
 */
export interface BreadcrumbItem {
  /** Unique identifier for the album */
  id: number;
  /** Display title for the breadcrumb */
  title: string;
  /** URL path for navigation */
  path: string;
}

/**
 * Breadcrumb path - array of breadcrumb items representing the full hierarchy
 *
 * The array is ordered from root to current album, with each item representing
 * one level in the album hierarchy.
 */
export type BreadcrumbPath = BreadcrumbItem[];

/**
 * Navigation state for managing current location and history
 *
 * Used to track the current navigation context and support browser history
 * integration with React Router.
 */
export interface NavigationState {
  /** Current album ID being viewed */
  currentAlbumId?: number;
  /** Current image ID being viewed (if in lightbox) */
  currentImageId?: number;
  /** Breadcrumb path for current location */
  breadcrumbPath: BreadcrumbPath;
}

/**
 * Note: Theme-related types are defined in:
 * - frontend/src/contexts/ThemeContext.tsx: Theme, ThemeContextValue
 * - frontend/src/config/themes.ts: ThemeName, ThemeDefinition
 *
 * The current theme system uses theme names (e.g., 'light', 'dark', 'classic') instead of preferences.
 * ThemeContextValue provides: theme, setTheme, availableThemes, isDark, isLight, isClassic
 *
 * The old types below (ThemeMode, ThemeColors, ThemeConfig, ThemeState, ThemeSwitcherProps) were from
 * earlier designs and are not used in the current implementation. They are kept
 * for reference but should not be imported or used.
 */

/**
 * @deprecated Use ThemePreference from ThemeContext instead
 * Theme mode - determines which theme is active
 */
export type ThemeMode = 'light' | 'dark' | 'system';

/**
 * @deprecated Not used in current implementation - themes use CSS variables
 * Theme color palette structure
 */
export interface ThemeColors {
  background: string;
  backgroundSecondary: string;
  text: string;
  textSecondary: string;
  accent: string;
  border: string;
  hover: string;
  focus: string;
  error: string;
  success: string;
}

/**
 * @deprecated Not used in current implementation - themes use CSS variables
 * Complete theme configuration
 */
export interface ThemeConfig {
  colors: ThemeColors;
  spacing: {
    xs: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
  };
  typography: {
    fontFamily: string;
    fontSize: {
      sm: string;
      md: string;
      lg: string;
      xl: string;
    };
  };
  borderRadius: {
    sm: string;
    md: string;
    lg: string;
  };
}

/**
 * @deprecated Use ThemeContextValue from ThemeContext instead
 * Theme state for theme context
 */
export interface ThemeState {
  mode: ThemeMode;
  config: ThemeConfig;
  setMode: (mode: ThemeMode) => void;
  toggleTheme: () => void;
}

/**
 * Filter criteria for filtering albums and images
 *
 * All properties are optional to support flexible filtering combinations.
 * Multiple filters can be applied simultaneously.
 */
export interface FilterCriteria {
  /** Date range filter (timestamps in milliseconds) */
  dateRange?: {
    /** Start timestamp (inclusive) */
    start: number;
    /** End timestamp (inclusive) */
    end: number;
  };
  /** Filter by item type */
  albumType?: 'GalleryAlbumItem' | 'GalleryPhotoItem' | 'all';
  /** Search query for text-based filtering */
  searchQuery?: string;
}

/**
 * Sort option - determines how items are sorted
 *
 * Format: '{field}-{direction}' where field is 'date', 'name', 'size', or 'order',
 * and direction is 'asc' (ascending) or 'desc' (descending). 'order' supports asc only.
 */
export type SortOption =
  | 'date-asc'
  | 'date-desc'
  | 'name-asc'
  | 'name-desc'
  | 'size-asc'
  | 'size-desc'
  | 'order-asc';

/**
 * Filter state - contains active filter criteria
 *
 * Used to manage the current filter state in the application.
 */
export interface FilterState {
  /** Active filter criteria */
  criteria: FilterCriteria;
  /** Function to update filter criteria */
  setCriteria: (criteria: FilterCriteria) => void;
  /** Function to clear all filters */
  clearFilters: () => void;
  /** Function to check if any filters are active */
  hasActiveFilters: () => boolean;
}

/**
 * Sort state - contains current sort option
 *
 * Used to manage the current sort state in the application.
 */
export interface SortState {
  /** Current sort option */
  option: SortOption;
  /** Function to set sort option */
  setOption: (option: SortOption) => void;
}

/**
 * Combined filter and sort state
 *
 * Convenience type that combines both filter and sort state for components
 * that need to manage both simultaneously.
 */
export interface FilterSortState {
  /** Filter state */
  filter: FilterState;
  /** Sort state */
  sort: SortState;
}

/**
 * Props for album component
 *
 * Used by components that display a single album.
 */
export interface AlbumProps {
  /** The album to display */
  album: Album;
  /** Optional click handler */
  onClick?: (album: Album) => void;
  /** Optional className for styling */
  className?: string;
}

/**
 * Props for image component
 *
 * Used by components that display a single image.
 */
export interface ImageProps {
  /** The image to display */
  image: Image;
  /** Optional click handler */
  onClick?: (image: Image) => void;
  /** Optional className for styling */
  className?: string;
  /** Whether to show thumbnail or full image */
  useThumbnail?: boolean;
}

/**
 * Props for album grid component
 *
 * Used by components that display multiple albums in a grid layout.
 */
export interface AlbumGridProps {
  /** Array of albums to display */
  albums: Album[];
  /** Optional loading state */
  isLoading?: boolean;
  /** Optional click handler for album selection */
  onAlbumClick?: (album: Album) => void;
  /** Optional className for styling */
  className?: string;
}

/**
 * Props for image grid component
 *
 * Used by components that display multiple images in a grid layout.
 * Can work with provided images prop or load data using albumId.
 */
export interface ImageGridProps {
  /** Array of images to display */
  images: Image[];
  /** Optional loading state */
  isLoading?: boolean;
  /** Optional click handler for image selection */
  onImageClick?: (image: Image) => void;
  /** Optional className for styling */
  className?: string;
}

/**
 * Props for breadcrumb component
 *
 * Used by components that display breadcrumb navigation.
 */
export interface BreadcrumbProps {
  /** Breadcrumb path to display */
  path: BreadcrumbPath;
  /** Optional click handler for breadcrumb items */
  onItemClick?: (item: BreadcrumbItem) => void;
  /** Optional className for styling */
  className?: string;
}

/**
 * @deprecated ThemeSwitcher has been replaced by ThemeDropdown.
 * Use ThemeDropdownProps from frontend/src/components/ThemeDropdown/ThemeDropdown.tsx instead.
 * ThemeDropdown only accepts className prop and uses useTheme hook internally.
 */
export interface ThemeSwitcherProps {
  currentMode: ThemeMode;
  onModeChange: (mode: ThemeMode) => void;
  className?: string;
}

/**
 * Props for filter panel component
 *
 * Used by components that provide filtering functionality.
 */
export interface FilterPanelProps {
  /** Current filter criteria */
  criteria: FilterCriteria;
  /** Function to update filter criteria */
  onCriteriaChange: (criteria: FilterCriteria) => void;
  /** Function to clear all filters */
  onClear?: () => void;
  /** Optional className for styling */
  className?: string;
}

/**
 * Props for sort dropdown component
 *
 * Used by components that provide sorting functionality.
 */
export interface SortDropdownProps {
  /** Current sort option */
  currentOption: SortOption;
  /** Function to set sort option */
  onOptionChange: (option: SortOption) => void;
  /** Optional className for styling */
  className?: string;
}

/**
 * Utility type: Extract albums from mixed array
 *
 * Filters an array of Child items to only include Albums.
 */
export type AlbumsOnly<T extends Child[]> = Extract<T[number], Album>[];

/**
 * Utility type: Extract images from mixed array
 *
 * Filters an array of Child items to only include Images.
 */
export type ImagesOnly<T extends Child[]> = Extract<T[number], Image>[];

/**
 * Utility type: Partial update for albums or images
 *
 * Allows partial updates to album or image properties.
 */
export type PartialAlbumOrImage<T extends AlbumOrImage> = Partial<
  Omit<T, 'id' | 'type'>
> &
  Pick<T, 'id' | 'type'>;

/**
 * Utility type: Readonly array of albums or images
 *
 * Creates a readonly array type for albums or images.
 */
export type ReadonlyAlbumOrImageArray<T extends AlbumOrImage[]> =
  ReadonlyArray<T[number]>;
